# Generated by Django 6.1.1 on 2026-09-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimNiveau',
            fields=[
                ('id_niv', models.AutoField(primary_key=True, serialize=False)),
                ('code_niv', models.CharField(db_index=True, max_length=20, unique=True)),
                ('libelle_niv', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'dim_niveau',
            },
        ),
        migrations.CreateModel(
            name='DimEtudiant',
            fields=[
                ('id_etu', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('annee_souscription', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'dim_etudiant',
                'indexes': [models.Index(fields=['nom', 'prenom'], name='dim_etudian_nom_ddcc0b_idx')],
            },
        ),
    ]
