# Generated by Django 6.1.1 on 2026-09-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAnneeAcademique',
            fields=[
                ('id_annee', models.AutoField(primary_key=True, serialize=False)),
                ('annee_academique', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'db_table': 'dim_annee_academique',
            },
        ),
        migrations.CreateModel(
            name='DimModule',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('code_mod', models.CharField(db_index=True, max_length=20)),
                ('nom_mod', models.CharField(max_length=150)),
                ('semestre', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'dim_module',
                'constraints': [models.UniqueConstraint(fields=('code_mod', 'semestre'), name='uniq_module_code_semestre')],
            },
        ),
        migrations.CreateModel(
            name='FactEvaluation',
            fields=[
                ('id_eval', models.AutoField(primary_key=True, serialize=False)),
                ('note_devoir1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_devoir2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_devoir3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_devoir4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_devoir_40', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des devoirs ramenée sur 40', max_digits=5, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_examen_60', models.DecimalField(blank=True, decimal_places=2, help_text="Note d'examen ramenée sur 60", max_digits=5, null=True)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultat', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('NON_EVALUE', 'Non évalué')], default='NON_EVALUE', max_length=20)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_rattrapage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultat_rattrapage', models.CharField(blank=True, choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('NON_EVALUE', 'Non évalué')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_annee', models.ForeignKey(db_column='id_annee', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.dimanneeacademique')),
                ('id_etu', models.ForeignKey(db_column='id_etu', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students.dimetudiant')),
                ('id_mod', models.ForeignKey(db_column='id_mod', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.dimmodule')),
                ('id_niv', models.ForeignKey(db_column='id_niv', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students.dimniveau')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'db_table': 'fact_evaluation',
                'indexes': [models.Index(fields=['id_niv'], name='fact_evalua_id_niv_191e27_idx'), models.Index(fields=['id_annee'], name='fact_evalua_id_anne_ba30a6_idx'), models.Index(fields=['id_mod'], name='fact_evalua_id_mod_eec979_idx'), models.Index(fields=['resultat'], name='fact_evalua_resulta_4392a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_etu', 'id_mod', 'id_niv', 'id_annee'), name='uniq_evaluation_quadruplet')],
            },
        ),
    ]
